### PR TITLE
Fixes setup.sh execution on Debian 8

### LINKED ISSUE #261: libssl-dev required for Ubuntu Server 14.04
Heya,
I just recently deployed the sync-engine for my own use on a new Ubuntu Server, 14.04 box and halfway through the pip install for cryptography library, it fails with 

`fatal error: openssl/aes.h: No such file or directory
     #include <openssl/aes.h>`

This is fixed by installing libssl-dev. I have not tested this on any other OS, or setup, so I'm not sure if this should be added to setup.sh, but I'd argue to err on the side of safety and add it to the list of packages installed via apt in the beginning.

### PR DESCRIPTION
**Pull request by singhkays**
Currently setup.sh keeps failing for me on a Debian 8 VM. Turns out the error is similar to here https://github.com/pyca/cryptography/issues/2280, which is due to apt installed of cffi version being less than 1.1. 

```
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-X8h31p-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/cryptography
Storing debug log for failure in /home/nikolai/.pip/pip.log
```

This PR also fixes #261 #267 #268 
-  setup.sh script now installs libssl-dev #261
- Update the minimum gevent version to 1.0.2 #267 
- added `cffi` to requirements.txt file which fixes the error in https://github.com/pyca/cryptography/issues/2280  and #268

### CODE REVIEW

**Comment by grinich** [comment]
Thanks! Can you sign the project's CLA? https://nylas.com/cla

**Comment by singhkay** [comment]
@grinich completed

**Comment by singhkay** [comment]
@grinich Any update on merging this?

**Comment by thurloat** [comment]
For me, all that was required was installing `libssl-dev` as a dependency.

**Comment by alexanderadam** [comment]
I just ran into [the same issues](https://github.com/nylas/sync-engine/issues/267) on Ubuntu 16.04.

It would be nice to hear at least why it isn't merged yet to get an update. It seems that, if you want to use Debian based Linux distributions, you aren't allow to use the current ones. :crying_cat_face:

**Comment by spang** [comment]
Rebased this and merged manually. Thank you for your contribution!

**Pull request closed without merging**
