### PR TITLE
Add index we added on production already to the application code.

### PR DESCRIPTION
**Pull request by spang**

### CODE REVIEW

**Comment by khamidou** [comment]
I have two questions and one remark:
1. Did Réne migrate all production shards?
2. Are we sure we need this index? IIRC this account has 4 Million events (!) --- it makes sense that getting the event list would take some time. What about preventing accounts from having that many events?
3. Can you add a migration?

**Comment by bengotow** [comment]
Hey folks! Just a driveby sidenote—it seems we should have `namespace, <default sort order>` indexes on all of our tables, since API queries are always scoped to a namespace? It looks like these don't exist on most of them, including `message` and `thread`? Maybe we should consider replacing the existing (non-namespace) indexes for common sort orders with ones that are prefixed with the namespace.

**Comment by khamidou** [comment]
@bengotow Sounds like a good idea but we should check with @renecannao before --- MySQL can be very non-intuitive!

**Comment by renecannao** [comment]
What said by @bengotow is generally correct, but it is true also what said by @khamidou .
To be more specific, if the queries have joins, or `WHERE` clauses against multiple fields, then should evaluated case by case what is the most efficient execution plan and if we should add an extra index.

**Pull request merged**
