### PR TITLE
Add username and secure flag to SMTP/IMAP accounts

### PR DESCRIPTION
**Pull request by thomasst**
This PR is based on the STARTTLS one (https://github.com/inboxapp/inbox/pull/125) and also fixes https://github.com/inboxapp/inbox/issues/110

* Added `AuthHandler.connect_to_imap` which connects to the IMAP endpoint but doesn't authenticate to avoid repeating code.
* Added support for non-SSL/TLS accounts using the `_imap_server_is_secure`/`_smtp_server_is_secure` flag. Endpoints are now a tuple of three items.
* Added support for custom SMTP/IMAP login usernames using the `imap_username`/`smtp_username` fields.

### CODE REVIEW

**Comment by philfreo** [comment]
:+1:

**Comment by grinich** [comment]
Thanks for this PR! We're still looking into this, and the best way to apply it. It impacts a few parts of our system and we want to have high confidence that we are defaulting to TLS in every situation possible. Thanks for your patience!

**Comment by florisgoumans** [comment]
@grinich this would be very useful!

**Comment by thomasst** [comment]
We should actually also have separate `imap_username` and `smtp_username` fields since I've seen setups where they're different.

**Comment by spang** [comment]
Yeah. We're aware, and are looking into that as well.

**Comment by kevinr** [comment]
+1

I just ran into this today, trying to do IMAP to work's mail server.  The sync engine is sending 'kevin@example.com' as my username, and the server expects just 'kevin'.

**Comment by tino** [comment]
I have the same problem with my Archiveopteryx mail server. Username != mailbox != alias.

**Comment by grinich** [comment]
I believe this is fixed in https://github.com/nylas/sync-engine/commit/269709d7e3737f439c2cbec7b46dd8669fd60b54 !

**Pull request closed without merging**
