### PR TITLE
add Postgres support

### PR DESCRIPTION
**Pull request by yedpodtrzitko**
- addes support for Postgres
- remove some duplicities in the code related to DB connection handling
- add missing dependency (faulthandler)

### CODE REVIEW

**Comment by spang** [comment]
Hey hey.

I thought about this a bit more, and I'm hesitant to merge support for Postgres officially since we don't run it in production and need to focus our time on driving the product forward in terms of features, performance, etc., rather than broadening our support for different database backends.

What do you think about creating a Postgres fork of the sync engine instead? We'd be happy to point folks looking for Postgres support at it, and that way you can make sure the Postgres support never breaks, by periodically rebasing on top of upstream master and testing the results.

**Comment by thomasst** [comment]
I'd be potentially interested in PostgreSQL support also. @yedpodtrzitko would you consider it stable or is there still work left?

**Comment by yedpodtrzitko** [comment]
@spang so... have you considered switching to Postgres? .)
Nah, just joking. Kind of.

My main interest is to use it, not making a fork, because keeping it up-to-date with the main repo would be quite demanding.
I can understand your concerns, however the code is backward-compatible, the default behaviour remains unchanged, as it just a bunch if `if-else`s replacing some DB-backend specific pieces in case the backend is changed on purpose.
 
@thomasst there is always a place for an improvement, however I havent encounter any error so far.

**Comment by grinich** [comment]
We're not going to support Postgres in any foreseeable future. This kind of change should live in a fork of the sync engine.

Thanks for putting in the work though-- I really appreciate it. If you're looking for bugs to fix or things to work on, jump in our Slack channel and say hi! :smile: :rocket: :raised_hands:  http://slack-invite.nylas.com/

**Pull request closed without merging**
