### PR TITLE
Add installation instructions of sync engine on DigitalOcean Droplet to README.md

### PR DESCRIPTION
**Pull request by adamporter**
Fixes #
N/A

Summary:
Adds detail to the README.md file to help others install the sync engine to a DigitalOcean Droplet.

Test Plan:
 N/A

Reviewers:
@grinich

### CODE REVIEW

**Comment by adamporter** [comment]
Hmm. Updating the README.md shouldn't have failed the Travis build.

**Comment by pfista** [comment]
Try rebasing on master again, the failure was due to a lint error that is fixed now.

**Comment by adamporter** [comment]
Biffed my local copy. Reset to upstream and recommitted my changes. Let's give this a whirl.

**Comment by khamidou** [comment]
Hi @adamporter,

Thanks for taking the time to send this pull request! 
I'm not an expert about using DigitalOcean w/ vagrant but I'm not seeing anything about securing the box here --- how do you prevent people from reading your emails or trying to ssh into your instance?

Cheers!

**Comment by YurySolovyov** [comment]
I wonder if its possible to use docker as engine to make it a bit more lightweight

**Comment by adamporter** [comment]
@YurySolovyov Here's a repo working toward that goal: https://github.com/nylas/sync-engine-docker

@khamidou Excellent questions. I must admit, I don't have **all** the answers. I had assumed that droplet security would be a separate concern, given that similar security measures would be taken with or without the sync engine in place. If you'd like, I can post my thoughts and links from DigitalOcean that address droplet security.

**Comment by YurySolovyov** [comment]
@adamporter the repo seems to have low activity, I guess it is not the Nylas team focus for now.

**Comment by adamporter** [comment]
@YurySolovyov That's correct. The README on that page actually says:
> Note this is not officially supported by Nylas.

**Comment by YurySolovyov** [comment]
@adamporter yeah, but no official support `!==` stalled. :smile: 
I still think this PR is useful. Thanks.

**Comment by adamporter** [comment]
@YurySolovyov No problem at all. My perspective is that there's low community interest, which means low value to the business. Why spend resources on features that aren't in high demand?

So, they're relying on the community to contribute. If you want it to work, **help** make it work. :+1:

**Comment by spang** [comment]
Hi there,

Given the lack of activity on this PR in the last 6 months, I'm going to go ahead and close it for now.

Feel free to reopen with a version that addresses the security concerns!

**Pull request closed without merging**
