### PR TITLE
Message filters

### PR DESCRIPTION
**Pull request by AdriVanHoudt**
This allow you to do
 `http://localhost:5555/messages?to=gleb@nylas.com&to=mg@nylas.com`
which will return all messages to gleb@nylas.com OR mg@nylas.com

### CODE REVIEW

**Comment by grinich** [comment]
Hm, I think we need to think about what adding this does to the semantics of the API. The rest of our filter parameters follow an "AND" terminology. Such as `?in=inbox&unread=true`. Adding the ability to create OR queries like this goes in a different direction. Why not just request each separately and combine them client-side?

**Comment by AdriVanHoudt** [comment]
It would take way more resources to do multiple requests, more data to transfer, processing we need to do at runtime that sql is designed to do.
The semantics don't change, the api is still an AND between all parameters only you allow a single param to match multiple values. It would not break any existing calls or expectations of the api.

**Comment by lievenjanssen** [comment]
To clarify a bit more a use case in our app would be that we want to get the last 50 emails exchanged between the account and 10 contacts between date X and date Y. If we need to support that from our end we will need to do 10 calls that each return 50 emails and we would need to order them on our end and only send back the last 50 emails to our client.

I think we all agree that this is a logic feature to add and that it is best implemented on the Nylas side maybe it's better to think through how to support OR instead of implementing a workaround at our end since the actual implementation is not that hard.

A suggestion I have is that we could only use the any_email param as an array, "any" suggests that any email can be involved.

**Comment by grinich** [comment]
I think we should allow the `any_email` param accept multiple comma-separated email address arguments that will match across any to/from/cc/bcc. These will be treated as an OR. You should be able to get what you want from this without it adding confusion of allowing multiple ULR query parameters with the same keys. Sound good?

**Comment by lievenjanssen** [comment]
Sounds good!

**Comment by grinich** [comment]
Going to work on it over here --> https://github.com/nylas/sync-engine/pull/273

**Pull request closed without merging**
