### PR TITLE
Email Aliases

### PR DESCRIPTION
**Pull request by EthanBlackburn**
I made the From: and Reply-To: headers both lists of (name, email) tuples as https://www.ietf.org/rfc/rfc2822.txt suggests. This meant I also had to add the Sender: header when From: contained more than one address.

### CODE REVIEW

**Comment by grinich** [comment]
Thanks for this patch @EthanBlackburn ! A few comments:

* I think we should leave out setting the Sender header. While this is indeed theoretically correct and is in the spec, in practice it's never set and I don't think most mail clients know how to display it. Maybe we should clarify our nomenclature for sender_name and the like
* Ditto for allowing multiple values in the `From` or `Reply-To` header. Let's constrain it to a single value. 
* Using a namedtuple for the from field is cool, but we don't do it anywhere else and in this situation we're not actually using the features of namedtuple. Just keep it a list (like the others) for simplicity right now.

**Comment by EthanBlackburn** [comment]
That makes sense. I wrestled with the idea of only allowing one address, but it looks like you have it as a list in base.py <code> message.from_addr = [(account.name, account.email_address)] </code>, so I just stuck with that. Should I change that as well?

**Comment by grinich** [comment]
It's fine to keep it as a list stored in the DB. I think we should just only allow one value through our API.

**Comment by EthanBlackburn** [comment]
It looks like some of the test cases have <code>Reply-To</code> as a list. I added <code>Reply-To</code> to the message obj in kellogs.py, and it fails on the second item(https://github.com/nylas/sync-engine/blob/1ee27d911848550bf2b2a932b676bae3bd384b4d/tests/data/base_dump.sql#L1176). Should <code>Reply-To</code> be a list in the DB?

**Comment by inboxskipper** [comment]
As an email list or stored as a list? We can still store it as a list, and should since the spec officially supports multiple items. I was just saying that the Nylas API should only allow users to specify one reply_to item when setting the optional API parameter.


On Apr 28, 2015, at 8:30 AM, Ethan Blackburn <notifications@github.com<mailto:notifications@github.com>> wrote:


It looks like some of the test cases have Reply-To as a list. I added Reply-To to the message obj in kellogs.py, and it fails on the second item(https://github.com/nylas/sync-engine/blob/1ee27d911848550bf2b2a932b676bae3bd384b4d/tests/data/base_dump.sql#L1176). Should Reply-To be a list in the DB?

-

**Comment by EthanBlackburn** [comment]
It's a list of lists(it fails on <code>[[u'Rui Ueyama', u'ruiu@google.com']]</code>). I was just confused because reply_to is a nullable field instead of defaulting to an empty list like from_addr does. Thus you have to check for None and a list of lists with only one element like so

```python
def format_address(address): 
    if address is None:
        return None
    if isinstance(address[0], list):
        address = address[0]
    name, email = address
    return {'name': name, 'email': email}
```

If it defaulted to a list in the DB you could use the same format_address_list as the other headers. Plus it would conform to the spec and we could still restrict it to one item in the API. But maybe that's a different issue and I should just go with the function above?

**Comment by EthanBlackburn** [comment]
Nevermind, I was overcomplicating that :)

**Comment by kav-ya** [comment]
Sweet, the patch looks good!
A few comments + stylistic suggestions -

* Update `draft_update_api()` (in inbox/api/ns_api.py) which calls `update_draft()` to pass in the additional arguments.

* I don't think  `message.from_addr = [(account.name, account.email_address) if not from_addr else from_addr]` does what you want; ('', '') is a Truthy value i.e.
```
> k = ('', '')
> m = [(1, 2) if not k else k]
> m
>  [('', '')]
```

* `get_mailbox` is ambiguous, rename it to be clearer (`get_recipient` is one option).

* In `send()` (inbox/sendmail/smtp/postel.py), it would be cleaner and less confusing to include a comment and do something like:
```
# from_addr is only ever a list with one element
from_addr = draft.from_addr[0]
msg = create_email(from_name=from_addr[0], 
                                from_email=from_addr[1],
                                 ...)
```

* Go ahead and update the docs so setting aliases is not a secret! =)
https://github.com/nylas/sync-engine/blob/master/inbox/docs/api/08_drafts.mdown

**Comment by EthanBlackburn** [comment]
How's that?

**Comment by kav-ya** [comment]
Very satisfactory; merged - thanks!

**Pull request closed without merging**
